fields:
  - name: deploy
    type: radio-fieldset
    values:
        - value: cc
          caption: Clean cluster with pre-deployed HelloWorld example
        - value: cmd
          caption: Deploy custom helm or stack via shell command
    default: cc
    showIf:
      cmd:
        name: cmd
        type: text
        height: 65
        required: true
        hideLabel: true
        default: |-
          OPERATOR_NAMESPACE=open-liberty
          kubectl create namespace "$OPERATOR_NAMESPACE"
          kubectl apply -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.0/openliberty-app-crd.yaml
          curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.0/openliberty-app-cluster-rbac.yaml | sed -e "s/OPEN_LIBERTY_OPERATOR_NAMESPACE/${OPERATOR_NAMESPACE}/"  | kubectl apply -f -
          curl -L https://raw.githubusercontent.com/OpenLiberty/open-liberty-operator/master/deploy/releases/0.7.0/openliberty-app-operator.yaml  | sed -e "s/OPEN_LIBERTY_WATCH_NAMESPACE/${OPERATOR_NAMESPACE}/"  | kubectl apply -n ${OPERATOR_NAMESPACE} -f -
          kubectl apply -f https://raw.githubusercontent.com/jelastic-jps/kubernetes/v1.18.12/addons/open-liberty.yaml

  - name: label
    caption: Topology
    type: displayfield
  - name: topo
    type: radio-fieldset
    values:
        - value: 0-dev
          caption: '<b>Development:</b> one master (1) and one scalable worker (1+)'
        - value: 1-prod
          caption: '<b>Production:</b> multi master (3) with API balancers (2+) and scalable workers (2+)'
    default: 0-dev

  - type: displayfield
    cls: warning
    height: 30
    hideLabel: true
    hidden: true
    markup:

  - name: ingress-controller
    type: list
    caption: Ingress Controller
    values:
      Nginx: Nginx
      HAProxy: HAProxy
      Traefik: Traefik
    default: Nginx
    hideLabel: false
    editable: false

  - name: dashboard
    type: list
    caption: Kubernetes Dashboard
    values:
      general: Kubernetes Dashboard v2
      k8dash: Kubernetes K8Dash
    default: general
    hideLabel: false
    editable: false

  - type: checkbox
    name: storage
    caption: Attach dedicated NFS Storage with dynamic volume provisioning
    value: true
    showIf:
      true:
      - type: checkbox
        name: monitoring
        caption: Install Prometheus & Grafana
        value: false

      - type: checkbox
        name: jaeger
        caption: Install Jaeger tracing tools
        value: false

      false:
      - type: checkbox
        name: monitoring
        caption: Install Prometheus & Grafana
        value: false
        disabled: true

      - type: checkbox
        name: jaeger
        caption: Install Jaeger tracing tools
        value: false
        disabled: true

  - type: checkbox
    name: api
    caption: Enable Remote API Access
    value: false

  - type: string
    name: version
    inputType: hidden
    caption: Kubernetes Version
    default: v1.18.10
